require "active_record"
require "rain_table"
ActiveRecord::Base.include(RainTable::ActiveRecord)

logger = ActiveSupport::Logger.new(STDOUT)
ActiveRecord::Base.logger = logger
ActiveSupport::LogSubscriber.colorize_logging = false

ActiveRecord::Migration.verbose = false

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

ActiveRecord::Schema.define do
  (2000...2100).each do |year|
    create_table "users_#{year}" do |t|
    end
  end
end

class User < ActiveRecord::Base
end

User.table_name = :users_2016
User.create!                    # => #<User id: 1>
User.table_name = :users_2017
User.create!                    # => #<User id: 1>
# >>    (0.5ms)  CREATE TABLE "users_2000" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2001" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2002" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2003" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2004" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2005" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2006" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2007" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2008" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2009" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2010" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2011" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2012" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2013" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2014" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2015" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2016" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2017" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2018" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2019" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (1.2ms)  CREATE TABLE "users_2020" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2021" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2022" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2023" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2024" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2025" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2026" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2027" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2028" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2029" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2030" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2031" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2032" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2033" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2034" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2035" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2036" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2037" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2038" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2039" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2040" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2041" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2042" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2043" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2044" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2045" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2046" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2047" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2048" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2049" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2050" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2051" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2052" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2053" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2054" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2055" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2056" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2057" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2058" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2059" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2060" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2061" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2062" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2063" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2064" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2065" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2066" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2067" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2068" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2069" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2070" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2071" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2072" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2073" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2074" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2075" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2076" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2077" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2078" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2079" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2080" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2081" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2082" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2083" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2084" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2085" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2086" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2087" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2088" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2089" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2090" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2091" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2092" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2093" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2094" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2095" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2096" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2097" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2098" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "users_2099" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
# >>    (0.1ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)
# >>   ActiveRecord::InternalMetadata Load (0.1ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", :environment], ["LIMIT", 1]]
# >>    (0.0ms)  begin transaction
# >>   SQL (0.1ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["key", "environment"], ["value", "default_env"], ["created_at", 2017-02-13 03:49:03 UTC], ["updated_at", 2017-02-13 03:49:03 UTC]]
# >>    (0.0ms)  commit transaction
# >>    (0.0ms)  begin transaction
# >>   SQL (0.0ms)  INSERT INTO "users_2016" DEFAULT VALUES
# >>    (0.0ms)  commit transaction
# >>    (0.0ms)  begin transaction
# >>   SQL (0.1ms)  INSERT INTO "users_2017" DEFAULT VALUES
# >>    (0.0ms)  commit transaction
